### PR TITLE
Fix StatusBar update in dark mode

### PR DESCRIPTION
**Pull request by robwayne**
### Checklist
- [x] I've run `bundle exec fastlane test` from the root directory to see all new and existing tests pass
- [x] I've followed the [vlc-ios code style](Docs/CodingStyle.md)
- [x] I've read the [Contribution Guidelines](https://github.com/videolan/vlc-ios#contribute)
- [x] I've updated the documentation if necessary.

### Description

This merge request updates the status bar in dark mode. fixes #403

### CODE REVIEW

**Comment by robwayne** [comment]
Note: my first contribution and the fastlane tests were not building for reasons I couldnt see why

**Comment by Mikanbu** [comment]
Hello,

Thank you for this PR!

There are small things that need to be addressed first git wise.

- Your name needs to be correctly configured to show your full name. You can achieve this by following this [guide from Github](https://help.github.com/en/articles/setting-your-username-in-git).
- In your various commit, there are changes that aren't related to this issue such as `.gitignore` or `*.lock` files modifications.

Other than the changes for fixing [#403](https://code.videolan.org/videolan/vlc-ios/issues/403) LTGM! 🎉

**Comment by Mikanbu** [comment]
Additionally, the spacing of the tab bar items seems wrong, perhaps something like is missing:

 `tabBarController.tabBar.itemPositioning = .fill`

**Comment by robwayne** [comment]
Hi thank you for reviewing! Sorry for the late reply, but I'll address the issues as soon as I can! Thanks

**Comment by carolanitz** [comment]
You can clean up and reduce it to two commits. One for removing the view controller, one for the statusbar with correct author as mentioned. Remove the .gitignore changes from this PR and @Mikanbu I believe the item position is unrelated to these changes right? So it could also be done in a follow up and after these changes it's good to merge :)

**Comment by Mikanbu** [comment]
@carolanitz I believe that the position is related to this change. I would say that it would be a regression if it wasn't part of this PR.
I didn't look into the details but the "hierarchical" change is probably/possibly be the reason.

**Comment by robwayne** [comment]
Hi guys, 
I'll be fixing this right now, sorry I was a bit busy for the past week. So should I make the item positioning fix in a followup commit as mentioned by @carolanitz ? 
Thanks

**Comment by Mikanbu** [comment]
I believe it shouldn't be a follow-up commit. It should be part of your modification.

**Comment by robwayne** [comment]
Okay thanks,
updated now!

**Comment by Mikanbu** [comment]
Almost done, just some changes that are hanging around which shouldn't be part of this PR:

- `.gitignore`
- `Gemfile.lock`
- `Podfile.lock`

**Comment by robwayne** [comment]
Oops my bad, don't know how I missed that. Fixed it now (hopefully last one lol)

**Comment by Mikanbu** [comment]
Merged with 4f4e0033810396c2b734748edfa36f3e07605db0.

I took the liberty of adjusting the author of the commit since it still was `robwayne`.

Thank you for the PR. 🎉

**Comment by Mikanbu** [comment]
Additionally, I realized that my suggestion about `itemPositioning` wasn't a fix for the issue. I decided to still merge this PR and we will address the issue later on.

Sorry about that.

**Pull request closed without merging**
