### PR TITLE
Actionsheet: Add theme observer (fixes #301)

### PR DESCRIPTION
**Pull request by mkchoi212**
### Checklist
- [x] I've run `bundle exec fastlane test` from the root directory to see all new and existing tests pass
- [x] I've followed the [vlc-ios code style](Docs/CodingStyle.md) and run `bundle exec fastlane lint` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/videolan/vlc-ios#contribute)
- [x] I've updated the documentation if necessary.

### Description

Theme observer code for VLCActionSheet's has been moved inside `VLCActionSheet.swift` to keep things contained.

Bug reference https://code.videolan.org/videolan/vlc-ios/issues/301

### CODE REVIEW

**Comment by Mikanbu** [comment]
IIRC, I put the theme code inside the `VLCRendererDiscovererManager` because the theme was related it. Meaning that since it is `VLCRendererDiscovererManager` that creates the action sheet,  it has the control over the sheet.
I don't mind this change, I can see the advantages, but wouldn't we lose the ability to customize it by component?

**Comment by mkchoi212** [comment]
Aren't all the actionsheets styled the same way? Or did I miss something in Figma :p

**Comment by carolanitz** [comment]
I believe this is the right change. As long as we don't need the ability to customize it by component somwhere we avoid this way that someone who uses this sheet has to think of this.

**Comment by carolanitz** [comment]
merged with f44b4a9c93d0e5311936957b106ce9341f6bc903

**Pull request closed without merging**
