### PR TITLE
key command: add playback speed key commands

### PR DESCRIPTION
**Pull request by AndrewSB**
`]` to increase playback rate by 50%
`[` to decrease playback rate by 25%
`=` to reset the playback rate, only shown when the playback rate isn't 1

### CODE REVIEW

**Comment by AndrewSB** [comment]
ping

would love to have this merged soon!

**Comment by carolanitz** [comment]
@Mikanbu that can be changed in a followup as well I believe

**Comment by carolanitz** [comment]
has been merged in with 484625492ec6a000da3fa509230288f46460583c 🎉

**Comment by AndrewSB** [comment]
@Mikanbu I tried to keep it consistent with the macOS shortcuts :) 

If we should change the amount, update here and I'm happy to open a new PR

**Pull request closed without merging**
