### PR TITLE
SwiftFormat integration

### PR DESCRIPTION
**Pull request by Tinkeacc**
### Checklist
- [x] I've run `bundle exec fastlane test` from the root directory to see all new and existing tests pass
- [x] I've followed the [vlc-ios code style](Docs/CodingStyle.md) and run `bundle exec fastlane lint` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/videolan/vlc-ios#contribute)
- [x] I've updated the documentation if necessary.

### Description

This is the VLC-iOS SwiftFormat integration (https://github.com/nicklockwood/SwiftFormat). I added SwiftFormat as a Xcode run script for VLC-iOS target. Due to my experience with SwiftFormat i disabled the following "magic" rules:
```blankLinesAtStartOfScope,hoistPatternLet,indent,redundantParens,redundantSelf,trailingCommas,unusedArguments,wrapArguments```
All SwiftFormat rules are described here: https://github.com/nicklockwood/SwiftFormat#rules

Full list of code changes:  
* Fixed inconsistent code - newline at end of functions / structs / computed properties
* Fixed inconsistent code - trailing colon for todos
* Fixed inconsistent code - blank line around marks
* Fixed inconsistent code - multiple spaces instead of one
* Fixed inconsistent code - space inside / at start of comments
* Fixed inconsistent code - trailing spaces for empty lines
* Fixed inconsistent code - space inside brackets
* Fixed inconsistent code - space inside parens
* Fixed inconsistent code - space inside braces
* Fixed inconsistent code - space around operators
* Fixed inconsistent code - code indent
* Fixed inconsistent code - order for access specifiers
* Fixed inconsistent code - redundant self reference
* Fixed inconsistent code - hex formatting
* Fixed inconsistent code - unnecessary nil initialization
* Fixed inconsistent code - no new trailing blank lines from inside braces, brackets, parens or chevrons
* Fixed inconsistent code - sorted imports
* Added SwiftFormat support for VLC-iOS debug schema
* Added run script phase for swiftFormat to VLC-iOS project

### CODE REVIEW

**Comment by Mikanbu** [comment]
Hi thank you for the PR, I do have a small question!

If I understood correctly, `SwiftFormat` is another formatting tool like `SwiftLint`?
If we want to have a more strict set of rules, wouldn't it be better to add it to the already in place `SwiftLint`?

**Comment by carolanitz** [comment]
From what I understood you use them in combination and SwiftFormat provides options Swiftlint doesn't but I might be wrong here. 
There is another important detail in this PR which is that it runs as build step and not with fastlane. You feedback as you write code. 
Additionally the pod is only integrated in debug which is something we should do for SwiftLint as well

**Comment by Mikanbu** [comment]
Which options does SwiftLint doesnt provide? Do we need them? By that I mean, does the additional options justify adding a whole new formatter?
If I'm not mistaken, if we want to have feedback with build you can achieve that with SwiftLint as well, but I'm not sure I would a 100% agree on adding this.

**Comment by carolanitz** [comment]
I let @Tinkeacc answer the benefits of SwiftFormat vs SwiftLint :) We should definitely adjust our code to move SwiftLint to the buildphase and only have it included in Debug.

**Comment by Tinkeacc** [comment]
Thx for the feedback. 

In general `SwiftFormat` is more a tool to prevent typos. Thats why i disabled "magic" rules like intend.

`SwiftLint` is able to do a autocorrection (`swiftlint autocorrect`), But the `:lint` fastlane lane in for vlc-ios does not contain swiftlint autocorrect. See `swiftlint(executable: 'Pods/SwiftLint/swiftlint', strict: true)`in https://github.com/videolan/vlc-ios/blob/master/fastlane/Fastfile. 
As i understand and how i configured `SwiftLint` is more like a tool that shows warnings or errors like in the readme of `SwiftLint`:
screenshot
My plan is to add `SwiftLint` as a buildtime phase as well where developers can see warnings or errors right after a build. But the problem is that vlc-ios actually is at around 50 warning and we should go down to something around 0. Then its easier to see and to understand the advantages of `SwiftLint` 😄 

Oh, i havent seen theintendation on `VLCActionSheet`. I did a `bundle exec fastlane lint` where i didnt see any errors. I checked the intend once and disabled the rule `indent` just to dont have any collision. Therefore i revert https://github.com/videolan/vlc-ios/pull/62/commits/26b54a4f98b404ae4d5538c8738e741f9f3bfdfa to fix this.

**Comment by Mikanbu** [comment]
I totally agree, I do too want to see the warnings gone from VLC-iOS!

Though I have to say that I'm quite confused...
The thing that confuses me is that you said: "your plan was to add `SwiftLint` as a buildtime phase..."
Did you mean `SwiftFormat`? If not, indeed `swiftlint autocorrect` isn't currently enabled in the lint lane but couldn't we enable it during for the build time phase and not add `SwiftFormat` to the project?

I must say that I'm not against `SwiftFormat`! I just want to understand it fully before adding it to the project. 😅

**Comment by Tinkeacc** [comment]
First of all, `SwiftLint` dont have the same rules as `SwiftFormat`. Just some like intend. `SwiftFormat` is more a helper tool to automatical fix small typos that you can see in my commits.

My plan is to add `SwiftLint `as a buildtime phase right after `SwiftFormat integration` was merged. Just to have both of them as a buildtime phase instead of use a lane in fastlane.

It is not a good idea to enable `swiftlint autocorrect`. `SwiftLint` is more a tool for issues where the developer need to manually change something like force casting (see the error in the picture above), force unwrapping or some defined styles like if line length is limited to 200 or something.

I implemented `SwiftLint `and `SwiftFormat` a year ago in our project and it reduced the "there is a typo", "dont do force unwrapping" copy and paste feedback in our pull requests.

**Comment by Tinkeacc** [comment]
@Mikanbu I reverted code intend related changes on `VLCActionSheet`.

**Comment by Tinkeacc** [comment]
@Mikanbu Sounds like a good plan. You can modify the PR.

**Comment by Mikanbu** [comment]
Thanks for the PR, merged with: `b544cab03cc365a33f998cb797da04ee7f72cf78`
For the `SwiftLint` part let's continue that on another PR!

**Pull request closed without merging**
