### PR TITLE
Adapt the tests to the new UI

### PR DESCRIPTION
**Pull request by dcordero**

### CODE REVIEW

**Comment by mkchoi212** [comment]
I started writing the new UI tests in Swift couple of hours ago and had no idea anyone was working on it :p

Should I stop or keep working on it?? @dcordero

**Comment by dcordero** [comment]
@mkchoi212  I did not either yhat you were migrating the test to Swift 😁

To safe the karma, I just adapted the current tests to the new UI, but without any migration to Swift at all. Is this generating a conflict with your migration task?

If your migration is also considering adapting the tests, my PR would be indeed redundant. Just let me know, what do you think?

I am happy to see the tests receiving love and tender 😊

**Comment by dcordero** [comment]
👌 As everything done here will be covered by your changes, I am closing this PR.

**Comment by mkchoi212** [comment]
@dcordero One quick question! Should UI tests support localized strings? Or just always test with en-US?

**Pull request closed without merging**
