### PR TITLE
Migrate Hockey to AppCenter

### PR DESCRIPTION
**Pull request by Mikanbu**
### Checklist
- [x] I've run `bundle exec fastlane test` from the root directory to see all new and existing tests pass
- [x] I've followed the [vlc-ios code style](Docs/CodingStyle.md)
- [x] I've read the [Contribution Guidelines](https://github.com/videolan/vlc-ios#contribute)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by Mikanbu** [comment]
Small issue that we need to consider.

For tvOS, it seems that AppCenter have a minimum target of tvOS 11, and we still support tvOS 10.2.

**Comment by carolanitz** [comment]
@Mikanbu can we wait with this until we have 3.2.0 out? I believe we still have 90 days and for the initial release It might be better to go with crashreporting that we're familiar with?

**Comment by Mikanbu** [comment]
@carolanitz I would be for migrating this. It doesn't seem that there are a lot of changes.

**Comment by jbkempf** [comment]
tvOS 10 is not an issue

**Comment by Mikanbu** [comment]
Rebased to master and include the tvOS migration as well.

**Comment by jbkempf** [comment]
LGTM

**Pull request merged**
