### PR TITLE
Architecture refactoring 

### PR DESCRIPTION
**Pull request by Mikanbu**
### Checklist
- [x] I've run `bundle exec fastlane test` from the root directory to see all new and existing tests pass
- [x] I've followed the [vlc-ios code style](Docs/CodingStyle.md) and run `bundle exec fastlane lint` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/videolan/vlc-ios#contribute)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by jbkempf** [comment]
This is not perfect, but this is a great step in the correct direction. So I'd say: ship it!

**Comment by Mikanbu** [comment]
Updated to recent master changes

**Comment by Mikanbu** [comment]
Fixed 🎉

**Comment by carolanitz** [comment]
merge please :)

**Comment by Mikanbu** [comment]
Sorry just one last commit for this PR!
As for the model names, it will be addressed in another PR, probably a medialibrary related one.

**Comment by carolanitz** [comment]
sure

**Comment by Mikanbu** [comment]
Merged.

**Pull request closed without merging**
